// Mock database — St. Gallen stores

export const initialTagData = {
    migros_sg: { bakery: 51, veggie: 18, dairy: 31, hot_meal: 0, drinks: 0, pastry: 0, savory: 0, organic: 0 },
    roggwiller: { bakery: 19, veggie: 0, dairy: 9, hot_meal: 0, drinks: 0, pastry: 72, savory: 0, organic: 0 },
    coop_restaurant: { bakery: 0, veggie: 27, dairy: 0, hot_meal: 58, drinks: 0, pastry: 0, savory: 15, organic: 0 },
    praline_scherrer: { bakery: 28, veggie: 0, dairy: 11, hot_meal: 0, drinks: 0, pastry: 61, savory: 0, organic: 0 },
    esswerk: { bakery: 0, veggie: 68, dairy: 0, hot_meal: 10, drinks: 0, pastry: 0, savory: 0, organic: 22 },
    barista: { bakery: 64, veggie: 0, dairy: 0, hot_meal: 0, drinks: 12, pastry: 24, savory: 0, organic: 0 },
    greco: { bakery: 12, veggie: 8, dairy: 18, hot_meal: 22, drinks: 0, pastry: 0, savory: 40, organic: 0 },
    chocolaterie_kloster: { bakery: 6, veggie: 0, dairy: 14, hot_meal: 0, drinks: 0, pastry: 68, savory: 0, organic: 12 },
    pinchu: { bakery: 0, veggie: 18, dairy: 0, hot_meal: 55, drinks: 8, pastry: 0, savory: 19, organic: 0 },
    brezelkoenig: { bakery: 72, veggie: 0, dairy: 0, hot_meal: 0, drinks: 6, pastry: 14, savory: 8, organic: 0 },
    tibits: { bakery: 0, veggie: 62, dairy: 5, hot_meal: 15, drinks: 0, pastry: 0, savory: 0, organic: 18 },
    kuhn: { bakery: 70, veggie: 0, dairy: 4, hot_meal: 0, drinks: 0, pastry: 22, savory: 4, organic: 0 },
};

export const stores = [
    {
        id: 'migros_sg',
        name: 'Migros Spisermarkt',
        emoji: '🛒',
        category: 'Supermarket',
        address: 'Marktplatz 15, St. Gallen',
        distance: '280m',
        distanceNum: 280,
        originalPrice: 'CHF 15.00',
        salePrice: 'CHF 4.90',
        price: 4.90,
        bags: 3,
        closingTime: '20:00',
        collectTimeStart: '18:30',
        collectTimeEnd: '20:00',
        rating: 4.3,
        ratingCount: 312,
        bgColor: '#3d8b3d',
        lat: 47.4253, lng: 9.3781,
        image: '/stores/migros.jpg',
        logo: '/stores/migros-logo.png',
        whatYouMightGet: ['🥖 Bread', '🥛 Dairy', '🥗 Salads', '🍎 Fruit'],
        section: 'recommended',
    },
    {
        id: 'roggwiller',
        name: 'Confiserie Roggwiller',
        emoji: '🍰',
        category: 'Confiserie & Café',
        address: 'Multergasse 17, St. Gallen',
        distance: '350m',
        distanceNum: 350,
        originalPrice: 'CHF 13.00',
        salePrice: 'CHF 3.90',
        price: 3.90,
        bags: 5,
        closingTime: '18:00',
        collectTimeStart: '17:00',
        collectTimeEnd: '18:00',
        rating: 4.7,
        ratingCount: 218,
        bgColor: '#8B6F5E',
        lat: 47.4244, lng: 9.3756,
        image: '/stores/roggwiller.jpg',
        logo: '/stores/roggwiller-logo',
        whatYouMightGet: ['🥐 Croissants', '🍰 Cakes', '🍫 Chocolates', '🧁 Pastries'],
        section: 'recommended',
    },
    {
        id: 'coop_restaurant',
        name: 'Coop Restaurant Marktgasse',
        emoji: '🍽️',
        category: 'Restaurant',
        address: 'Marktgasse 9, St. Gallen',
        distance: '420m',
        distanceNum: 420,
        originalPrice: 'CHF 18.00',
        salePrice: 'CHF 5.90',
        price: 5.90,
        bags: 2,
        closingTime: '21:00',
        collectTimeStart: '19:30',
        collectTimeEnd: '21:00',
        rating: 4.1,
        ratingCount: 145,
        bgColor: '#C0390A',
        lat: 47.4241, lng: 9.3771,
        image: '/stores/coop.png',
        logo: '/stores/Coop-logo.svg.png',
        whatYouMightGet: ['🥗 Salads', '🍲 Hot dishes', '🥤 Drinks', '🍞 Bread'],
        section: 'save_soon',
    },
    {
        id: 'praline_scherrer',
        name: 'Praliné Scherrer',
        emoji: '🍫',
        category: 'Chocolaterie',
        address: 'Marktgasse 28, St. Gallen',
        distance: '500m',
        distanceNum: 500,
        originalPrice: 'CHF 14.00',
        salePrice: 'CHF 4.50',
        price: 4.50,
        bags: 4,
        closingTime: '18:30',
        collectTimeStart: '17:30',
        collectTimeEnd: '18:30',
        rating: 4.5,
        ratingCount: 189,
        bgColor: '#5C3317',
        lat: 47.4243, lng: 9.3767,
        image: '/stores/praline.jpg',
        logo: '/stores/praline-logo.png',
        whatYouMightGet: ['🍫 Pralines', '🍬 Confectionery', '🎂 Cakes', '🍮 Desserts'],
        section: 'save_soon',
    },
    {
        id: 'esswerk',
        name: 'Esswerk',
        emoji: '🥗',
        category: 'Organic Restaurant',
        address: 'Oberer Graben 3, St. Gallen',
        distance: '650m',
        distanceNum: 650,
        originalPrice: 'CHF 17.00',
        salePrice: 'CHF 5.50',
        price: 5.50,
        bags: 3,
        closingTime: '21:30',
        collectTimeStart: '20:00',
        collectTimeEnd: '21:30',
        rating: 4.6,
        ratingCount: 267,
        bgColor: '#4a7c4e',
        lat: 47.4256, lng: 9.3745,
        image: '/stores/esswerk.jpg',
        logo: '/stores/esswerk-logo.png',
        whatYouMightGet: ['🌯 Burritos', '🥣 Bowls', '🥗 Salads', '🌱 Organic dishes'],
        section: 'nearby',
    },
    {
        id: 'barista',
        name: 'Barista Specialty Coffee',
        emoji: '☕',
        category: 'Coffee & Bakery',
        address: 'Blumenbergplatz 1, St. Gallen',
        distance: '180m',
        distanceNum: 180,
        originalPrice: 'CHF 11.00',
        salePrice: 'CHF 3.50',
        price: 3.50,
        bags: 6,
        closingTime: '17:00',
        collectTimeStart: '16:00',
        collectTimeEnd: '17:00',
        rating: 4.8,
        ratingCount: 431,
        bgColor: '#2C1810',
        lat: 47.4263, lng: 9.3736,
        image: '/stores/barista.jpg',
        logo: '/stores/barista-logo.png',
        whatYouMightGet: ['☕ Coffee', '🥐 Pastries', '🍞 Sandwiches', '🧁 Muffins'],
        section: 'nearby',
    },
    {
        id: 'greco',
        name: 'Greco Fine Food',
        emoji: '🫒',
        category: 'Fine Food & Deli',
        address: 'Spisergasse 12, St. Gallen',
        distance: '310m',
        distanceNum: 310,
        originalPrice: 'CHF 16.00',
        salePrice: 'CHF 4.90',
        price: 4.90,
        bags: 3,
        closingTime: '19:00',
        collectTimeStart: '17:30',
        collectTimeEnd: '19:00',
        rating: 4.4,
        ratingCount: 176,
        bgColor: '#6B4226',
        lat: 47.4252, lng: 9.3791,
        image: '/stores/greco.jpeg',
        logo: '/stores/greco-logo.jpeg',
        whatYouMightGet: ['🫒 Olives', '🧀 Cheese', '🥩 Charcuterie', '🥖 Focaccia'],
        section: 'recommended',
    },
    {
        id: 'chocolaterie_kloster',
        name: 'Chocolaterie am Klosterplatz',
        emoji: '🍫',
        category: 'Chocolaterie & Pastry',
        address: 'Klosterplatz 2, St. Gallen',
        distance: '400m',
        distanceNum: 400,
        originalPrice: 'CHF 14.00',
        salePrice: 'CHF 4.20',
        price: 4.20,
        bags: 4,
        closingTime: '18:30',
        collectTimeStart: '17:00',
        collectTimeEnd: '18:30',
        rating: 4.6,
        ratingCount: 203,
        bgColor: '#4A2C1A',
        lat: 47.4235, lng: 9.3759,
        image: '/stores/chocolaterie.jpg',
        logo: '/stores/chocolaterie-logo.png',
        whatYouMightGet: ['🍫 Pralines', '🍰 Tarts', '🧁 Pastries', '🍮 Mousse'],
        section: 'save_soon',
    },
    {
        id: 'pinchu',
        name: 'PinChu',
        emoji: '🥟',
        category: 'Asian Food',
        address: 'Goliathgasse 8, St. Gallen',
        distance: '450m',
        distanceNum: 450,
        originalPrice: 'CHF 16.00',
        salePrice: 'CHF 5.50',
        price: 5.50,
        bags: 2,
        closingTime: '21:00',
        collectTimeStart: '19:00',
        collectTimeEnd: '21:00',
        rating: 4.3,
        ratingCount: 138,
        bgColor: '#B91C1C',
        lat: 47.4232, lng: 9.3750,
        image: '/stores/pinchu.jpg',
        logo: '/stores/pinchu-logo.png',
        whatYouMightGet: ['🥟 Dumplings', '🍜 Noodles', '🍚 Rice bowls', '🥢 Stir fry'],
        section: 'nearby',
    },
    {
        id: 'brezelkoenig',
        name: 'Brezelkönig - Bahnhof St. Gallen',
        emoji: '🥨',
        category: 'Bakery',
        address: 'Bahnhofplatz 1, St. Gallen',
        distance: '550m',
        distanceNum: 550,
        originalPrice: 'CHF 10.00',
        salePrice: 'CHF 3.50',
        price: 3.50,
        bags: 5,
        closingTime: '19:30',
        collectTimeStart: '18:00',
        collectTimeEnd: '19:30',
        rating: 4.2,
        ratingCount: 287,
        bgColor: '#92400E',
        lat: 47.4238, lng: 9.3699,
        image: '/stores/brezelkonig.jpg.webp',
        logo: '/stores/brezelkonig-logo.png',
        whatYouMightGet: ['🥨 Pretzels', '🥖 Baguettes', '🥐 Croissants', '🧁 Sweet rolls'],
        section: 'recommended',
    },
    {
        id: 'tibits',
        name: 'tibits - St. Gallen',
        emoji: '🥗',
        category: 'Vegetarian Restaurant',
        address: 'Bankgasse 4, St. Gallen',
        distance: '480m',
        distanceNum: 480,
        originalPrice: 'CHF 18.00',
        salePrice: 'CHF 5.90',
        price: 5.90,
        bags: 3,
        closingTime: '21:00',
        collectTimeStart: '19:30',
        collectTimeEnd: '21:00',
        rating: 4.5,
        ratingCount: 324,
        bgColor: '#15803D',
        lat: 47.4230, lng: 9.3711,
        image: '/stores/tibits.jpg',
        logo: '/stores/tibits-logo.png',
        whatYouMightGet: ['🥗 Salads', '🍛 Curries', '🥙 Wraps', '🌱 Vegan bowls'],
        section: 'save_soon',
    },
    {
        id: 'kuhn',
        name: 'Bäckerei Kuhn - Neumarkt',
        emoji: '🥖',
        category: 'Bakery',
        address: 'Neumarkt 3, St. Gallen',
        distance: '600m',
        distanceNum: 600,
        originalPrice: 'CHF 12.00',
        salePrice: 'CHF 3.90',
        price: 3.90,
        bags: 4,
        closingTime: '18:00',
        collectTimeStart: '16:30',
        collectTimeEnd: '18:00',
        rating: 4.7,
        ratingCount: 356,
        bgColor: '#A16207',
        lat: 47.4216, lng: 9.3713,
        image: '/stores/kuhn.jpg',
        logo: '/stores/kuhn-logo.svg.png',
        whatYouMightGet: ['🥖 Bread', '🥐 Pastries', '🍰 Cakes', '🧁 Muffins'],
        section: 'nearby',
    },
];

export const initialQuestProgress = { q1: 5, q2: 1, q3: 2, q4: 2 };

export const quests = [
    { id: 'q1', icon: '🏷️', title: 'Tag Master', description: 'Tag 5 bags this week · saves ~2.5kg CO₂', total: 5, points: 50 },
    { id: 'q2', icon: '🏷️', title: 'Tag Contributor', description: 'Tag 3 bags · help others know what to expect', total: 3, points: 30 },
    { id: 'q3', icon: '🔥', title: 'Streak Builder', description: 'Save bags 3 days in a row · 3 meals rescued', total: 3, points: 40 },
    { id: 'q4', icon: '🌍', title: 'Eco Explorer', description: 'Discover 4 stores · reduce local food waste', total: 4, points: 60 },
];

export const badges = [
    { id: 'b1', name: 'Eco Starter', emoji: '🌱', earned: true, desc: 'Save your first surprise bag' },
    { id: 'b2', name: 'First Review', emoji: '⭐', earned: true, desc: 'Leave your first community tag' },
    { id: 'b3', name: '3-Day Streak', emoji: '🔥', earned: true, desc: 'Save bags 3 days in a row' },
    { id: 'b4', name: 'Explorer', emoji: '🧭', earned: true, desc: 'Try 5 different stores' },
    { id: 'b5', name: 'Night Owl', emoji: '🦉', earned: true, desc: 'Pick up a bag after 8 PM' },
    { id: 'b6', name: 'Veggie Hero', emoji: '🥬', earned: true, desc: 'Save 3 bags from veggie stores' },
    { id: 'b7', name: 'Early Bird', emoji: '🐦', earned: true, desc: 'Reserve a bag within 1 min of posting' },
    { id: 'b8', name: 'Tag Master', emoji: '🏷️', earned: true, desc: 'Leave 10 community tags' },
    { id: 'b9', name: '7-Day Streak', emoji: '💪', earned: false, desc: 'Save bags 7 days in a row' },
    { id: 'b10', name: 'Champion', emoji: '🏆', earned: false, desc: 'Reach the top 3 on the leaderboard' },
    { id: 'b11', name: 'Earth Saver', emoji: '🌍', earned: false, desc: 'Save 50 kg of CO₂' },
    { id: 'b12', name: 'Social Butterfly', emoji: '🦋', earned: false, desc: 'Invite 5 friends who sign up' },
    { id: 'b13', name: 'Bakery Lover', emoji: '🥐', earned: false, desc: 'Save 10 bags from bakeries' },
    { id: 'b14', name: 'Zero Waste', emoji: '♻️', earned: false, desc: 'Complete all weekly quests for a month' },
    { id: 'b15', name: 'Local Legend', emoji: '👑', earned: false, desc: 'Save 100 bags in St. Gallen' },
    { id: 'b16', name: 'Sharing Hero', emoji: '🤝', earned: false, desc: 'Share 10 store recommendations' },
];

export const leaderboard = [
    { rank: 1, name: 'Lukas G.', points: 1380, isYou: false },
    { rank: 2, name: 'Egor A.', points: 1210, isYou: false },
    { rank: 3, name: 'You', points: 1045, isYou: true },
    { rank: 4, name: 'Mateo O.', points: 980, isYou: false },
    { rank: 5, name: 'Mia B.', points: 920, isYou: false },
    { rank: 6, name: 'Nina T.', points: 860, isYou: false },
    { rank: 7, name: 'Florian M.', points: 790, isYou: false },
    { rank: 8, name: 'Ainhoa E.', points: 740, isYou: false },
    { rank: 9, name: 'Anastasija P.', points: 680, isYou: false },
    { rank: 10, name: 'Marta C.', points: 620, isYou: false },
    { rank: 11, name: 'Janik S.', points: 560, isYou: false },
    { rank: 12, name: 'Michel S.', points: 510, isYou: false },
    { rank: 13, name: 'Sofonias T.', points: 450, isYou: false },
    { rank: 14, name: 'Adriana B.', points: 390, isYou: false },
    { rank: 15, name: 'Anika S.', points: 340, isYou: false },
];
