// Mock database — St. Gallen stores

export const initialTagData = {
    migros_sg: { bakery: 51, veggie: 18, dairy: 31, hot_meal: 0, drinks: 0, pastry: 0, savory: 0, organic: 0 },
    roggwiller: { bakery: 19, veggie: 0, dairy: 9, hot_meal: 0, drinks: 0, pastry: 72, savory: 0, organic: 0 },
    coop_restaurant: { bakery: 0, veggie: 27, dairy: 0, hot_meal: 58, drinks: 0, pastry: 0, savory: 15, organic: 0 },
    praline_scherrer: { bakery: 28, veggie: 0, dairy: 11, hot_meal: 0, drinks: 0, pastry: 61, savory: 0, organic: 0 },
    esswerk: { bakery: 0, veggie: 68, dairy: 0, hot_meal: 10, drinks: 0, pastry: 0, savory: 0, organic: 22 },
    barista: { bakery: 64, veggie: 0, dairy: 0, hot_meal: 0, drinks: 12, pastry: 24, savory: 0, organic: 0 },
};

export const stores = [
    {
        id: 'migros_sg',
        name: 'Migros Marktplatz',
        emoji: '🛒',
        category: 'Supermarket',
        address: 'Marktplatz 15, St. Gallen',
        distance: '280m',
        distanceNum: 280,
        originalPrice: 'CHF 15.00',
        salePrice: 'CHF 4.90',
        price: 4.90,
        bags: 3,
        closingTime: '20:00',
        collectTimeStart: '18:30',
        collectTimeEnd: '20:00',
        rating: 4.3,
        ratingCount: 312,
        bgColor: '#3d8b3d',
        image: '/stores/migros.jpg',
        logo: '/stores/migros-logo.png',
        whatYouMightGet: ['🥖 Bread', '🥛 Dairy', '🥗 Salads', '🍎 Fruit'],
        section: 'recommended',
    },
    {
        id: 'roggwiller',
        name: 'Confiserie Roggwiller',
        emoji: '🍰',
        category: 'Confiserie & Café',
        address: 'Multergasse 17, St. Gallen',
        distance: '350m',
        distanceNum: 350,
        originalPrice: 'CHF 13.00',
        salePrice: 'CHF 3.90',
        price: 3.90,
        bags: 5,
        closingTime: '18:00',
        collectTimeStart: '17:00',
        collectTimeEnd: '18:00',
        rating: 4.7,
        ratingCount: 218,
        bgColor: '#8B6F5E',
        image: '/stores/roggwiller.jpg',
        logo: '/stores/roggwiller-logo',
        whatYouMightGet: ['🥐 Croissants', '🍰 Cakes', '🍫 Chocolates', '🧁 Pastries'],
        section: 'recommended',
    },
    {
        id: 'coop_restaurant',
        name: 'Coop Restaurant Marktgasse',
        emoji: '🍽️',
        category: 'Restaurant',
        address: 'Marktgasse 9, St. Gallen',
        distance: '420m',
        distanceNum: 420,
        originalPrice: 'CHF 18.00',
        salePrice: 'CHF 5.90',
        price: 5.90,
        bags: 2,
        closingTime: '21:00',
        collectTimeStart: '19:30',
        collectTimeEnd: '21:00',
        rating: 4.1,
        ratingCount: 145,
        bgColor: '#C0390A',
        image: '/stores/coop.png',
        logo: '/stores/Coop-logo.svg.png',
        whatYouMightGet: ['🥗 Salads', '🍲 Hot dishes', '🥤 Drinks', '🍞 Bread'],
        section: 'save_soon',
    },
    {
        id: 'praline_scherrer',
        name: 'Praliné Scherrer',
        emoji: '🍫',
        category: 'Chocolaterie',
        address: 'Marktgasse 28, St. Gallen',
        distance: '500m',
        distanceNum: 500,
        originalPrice: 'CHF 14.00',
        salePrice: 'CHF 4.50',
        price: 4.50,
        bags: 4,
        closingTime: '18:30',
        collectTimeStart: '17:30',
        collectTimeEnd: '18:30',
        rating: 4.5,
        ratingCount: 189,
        bgColor: '#5C3317',
        image: '/stores/praline.jpg',
        logo: '/stores/praline-logo.png',
        whatYouMightGet: ['🍫 Pralines', '🍬 Confectionery', '🎂 Cakes', '🍮 Desserts'],
        section: 'save_soon',
    },
    {
        id: 'esswerk',
        name: 'Esswerk',
        emoji: '🥗',
        category: 'Organic Restaurant',
        address: 'Oberer Graben 3, St. Gallen',
        distance: '650m',
        distanceNum: 650,
        originalPrice: 'CHF 17.00',
        salePrice: 'CHF 5.50',
        price: 5.50,
        bags: 3,
        closingTime: '21:30',
        collectTimeStart: '20:00',
        collectTimeEnd: '21:30',
        rating: 4.6,
        ratingCount: 267,
        bgColor: '#4a7c4e',
        image: '/stores/esswerk.jpg',
        logo: '/stores/esswerk-logo.png',
        whatYouMightGet: ['🌯 Burritos', '🥣 Bowls', '🥗 Salads', '🌱 Organic dishes'],
        section: 'nearby',
    },
    {
        id: 'barista',
        name: 'Barista Specialty Coffee',
        emoji: '☕',
        category: 'Coffee & Bakery',
        address: 'Blumenbergplatz 1, St. Gallen',
        distance: '180m',
        distanceNum: 180,
        originalPrice: 'CHF 11.00',
        salePrice: 'CHF 3.50',
        price: 3.50,
        bags: 6,
        closingTime: '17:00',
        collectTimeStart: '16:00',
        collectTimeEnd: '17:00',
        rating: 4.8,
        ratingCount: 431,
        bgColor: '#2C1810',
        image: '/stores/barista.jpg',
        logo: '/stores/barista-logo.png',
        whatYouMightGet: ['☕ Coffee', '🥐 Pastries', '🍞 Sandwiches', '🧁 Muffins'],
        section: 'nearby',
    },
];

export const initialQuestProgress = { q1: 5, q2: 1, q3: 2, q4: 2 };

export const quests = [
    { id: 'q1', icon: '🏷️', title: 'Tag Master',     description: 'Tag 5 bags this week · saves ~2.5kg CO₂',           total: 5, points: 50 },
    { id: 'q2', icon: '🏷️',  title: 'Tag Contributor',  description: 'Tag 3 bags · help others know what to expect',        total: 3, points: 30 },
    { id: 'q3', icon: '🔥',  title: 'Streak Builder', description: 'Save bags 3 days in a row · 3 meals rescued',         total: 3, points: 40 },
    { id: 'q4', icon: '🌍',  title: 'Eco Explorer',   description: 'Discover 4 stores · reduce local food waste',         total: 4, points: 60 },
];

export const badges = [
    { id: 'b1', name: 'Eco Starter',  emoji: '🌱', earned: true  },
    { id: 'b2', name: 'First Review', emoji: '⭐', earned: true  },
    { id: 'b3', name: '3-Day Streak', emoji: '🔥', earned: true  },
    { id: 'b4', name: 'Explorer',     emoji: '🧭', earned: false },
    { id: 'b5', name: 'Champion',     emoji: '🏆', earned: false },
    { id: 'b6', name: 'Earth Saver',  emoji: '🌍', earned: false },
];

export const leaderboard = [
    { rank: 1,  name: 'Lukas G.',       points: 1380, isYou: false },
    { rank: 2,  name: 'Egor A.',        points: 1210, isYou: false },
    { rank: 3,  name: 'You',            points: 1045, isYou: true  },
    { rank: 4,  name: 'Mateo O.',       points: 980,  isYou: false },
    { rank: 5,  name: 'Mia B.',         points: 920,  isYou: false },
    { rank: 6,  name: 'Nina T.',        points: 860,  isYou: false },
    { rank: 7,  name: 'Florian M.',     points: 790,  isYou: false },
    { rank: 8,  name: 'Ainhoa E.',      points: 740,  isYou: false },
    { rank: 9,  name: 'Anastasija P.',  points: 680,  isYou: false },
    { rank: 10, name: 'Marta C.',       points: 620,  isYou: false },
    { rank: 11, name: 'Janik S.',       points: 560,  isYou: false },
    { rank: 12, name: 'Michel S.',      points: 510,  isYou: false },
    { rank: 13, name: 'Sofonias T.',    points: 450,  isYou: false },
    { rank: 14, name: 'Adriana B.',     points: 390,  isYou: false },
    { rank: 15, name: 'Anika S.',       points: 340,  isYou: false },
];
